core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("",include("nomina.urls")),
    path('admin/', admin.site.urls),
]

nomina/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path("",Inicio, name="Inicio"),
    path("listado/",Empleados, name="Lista"),
    path("departamento_listado/",Departamentos, name='ListadoDepartamento'),
    path("cargo_listado/",Cargos, name='ListadoCargo'),
    path("contrato_listado/",Contrato, name='ListadoContrato'),
    path("nominas_listado/",Nominas, name='ListadoNominas'),
    path("Secion/",Secion,name="Secion"),
    path("singout/",singout,name="singout"),
    path("signin/",signin,name="signin"),
    # Urls de creacion
    path("crear_empleado",CrearEmpleado, name="Crear_Empleado"),
    path("crear_nominas/",CrearNominas,name="Crear_Nomina"),
    path("crear_cargo/",CrearCargo,name="Crear_Cargo"),
    path("crear_departamento/",CrearDepartamento,name="Crear_Departamento"),
    path("crear_contrato/",CrearContrato,name="Crear_Contrato"),
    # Urls de Update
    path("update_empleado/<int:id>/",UpdateEmpleado,name="Update_Empleado"),
    path("update_nomina/<int:id>/",UpdateNomina,name="Update_Nomina"),
    path("update_cargo/<int:id>/",UpdateCargo,name="Update_Cargo"),
    path("update_departamento/<int:id>/",UpdateDepartamento,name="Update_Departamento"),
    path("update_contrato/<int:id>/",UpdateContrato,name="Update_Contrato"),
    path('delate/<str:modelo>/<int:id>',Eliminar,name="Eliminar")
]

nomina/models.py
from django.db import models

# Create your models here.
from django.db import models

class Cargo(models.Model):
    descripcion = models.CharField(max_length=100)
    def __str__(self):
        return self.descripcion

class Departamento(models.Model):
    descripcion = models.CharField(max_length=100)
    def __str__(self):
        return self.descripcion

class TipoContrato(models.Model):
    descripcion = models.CharField(max_length=100)
    def __str__(self):
        return self.descripcion


class Empleado(models.Model):
    SEXO_CHOICES = [
    ('M', 'Masculino'),
    ('F', 'Femenino'),
    ]

    nombre = models.CharField(max_length=100)
    cedula = models.CharField(max_length=20, unique=True)
    direccion = models.TextField()
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)
    sueldo = models.DecimalField(max_digits=10, decimal_places=2)
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE)
    departamento = models.ForeignKey(Departamento,
    on_delete=models.CASCADE)
    tipo_contrato = models.ForeignKey(TipoContrato,
    on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Rol(models.Model):
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    aniomes = models.DateField()#202501
    sueldo = models.DecimalField(max_digits=10, decimal_places=2)
    horas_extra = models.DecimalField(max_digits=10, decimal_places=2)
    bono = models.DecimalField(max_digits=10, decimal_places=2)
    iess = models.DecimalField(max_digits=10, decimal_places=2)
    tot_ing = models.DecimalField(max_digits=10, decimal_places=2)
    tot_des = models.DecimalField(max_digits=10, decimal_places=2)
    neto = models.DecimalField(max_digits=10, decimal_places=2)

nomina/forms.py
#!/usr/bin/env python3
from django.forms import CharField, ChoiceField, ModelForm, ModelChoiceField, DateField, DecimalField, NumberInput, Select, TextInput, DateInput
from .models import Cargo, Departamento, Empleado, Rol, TipoContrato

class RolPago(ModelForm):
    empleado = ModelChoiceField(
        queryset = Empleado.objects.all(),
        label = "Empleado",
        empty_label="Seleccione el empleado",
        widget=Select(attrs={'class':'form-select'})
    )
    aniomes = DateField(label="Anio y mes", widget=DateInput(attrs={'type':'date','class':'form-control'}))
    horas_extra = DecimalField(label="Horas extras",widget=NumberInput(attrs={'class':'form-control'}))
    bono = DecimalField(label="Bono",widget=NumberInput(attrs={'class':'form-control'}))

    class Meta:
        model = Rol
        fields = ["empleado","aniomes","horas_extra","bono"]

class EmpleadoForm(ModelForm):
    nombre = CharField(widget=TextInput(attrs={'class':'form-control'}))
    cedula = CharField(widget=TextInput(attrs={'class':'form-control'}))
    direccion = CharField(widget=TextInput(attrs={'class':'form-control'}))
    sexo = ChoiceField(
        choices=Empleado.SEXO_CHOICES,
        widget=Select(attrs={'class':'form-control'})
    )
    sueldo = DecimalField(widget=NumberInput(attrs={'class':'form-control'}))
    cargo = ModelChoiceField(
        queryset=Cargo.objects.all(),
        empty_label="Seleccione el cargo",
        widget=Select(attrs={'class':'form-select'})
    )

    departamento = ModelChoiceField(
        queryset=Departamento.objects.all(),
        empty_label="Seleccione su departamento",
        widget=Select(attrs={'class':'form-select'})
    )

    tipo_contrato = ModelChoiceField(
        queryset=TipoContrato.objects.all(),
        empty_label="Seleccione su tipo de contrato",
        widget=Select(attrs={'class':'form-select'})
    )

    class Meta:
        model = Empleado
        fields = ["nombre","cedula","direccion","sexo","sueldo","cargo","departamento","tipo_contrato"]

class FormDepartamento(ModelForm):
    descripcion = CharField(widget=TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = Departamento
        fields = ['descripcion']

class FormCargo(ModelForm):
    descripcion = CharField(widget=TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = Cargo
        fields = ['descripcion']

class FormContrato(ModelForm):
    descripcion = CharField(widget=TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = TipoContrato
        fields = ['descripcion']

nomina/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.db import IntegrityError
from nomina.forms import EmpleadoForm, FormCargo, FormContrato, FormDepartamento, RolPago
from nomina.models import Cargo, Departamento, Empleado, Rol, TipoContrato

# Create your views here.

# Vistas para presentar
def Inicio(request):
    return render(request,'Inicio.jinja')

def Empleados(request):
    empleados = Empleado.objects.all()
    empleados_dict = [{"id":emp.pk,"Nombre":emp.nombre, "Cedula":emp.cedula,"Direccion":emp.direccion,"Sexo":emp.sexo,"Sueldo":emp.sueldo,"Cargo":emp.cargo.descripcion,"Departamento":emp.departamento.descripcion,"Contrato":emp.tipo_contrato.descripcion} for emp in empleados]
    return render(request, 'lista_nominas.jinja',{"table_body":empleados_dict})

def Secion(request):
    if request.method == "GET":
        return render(request,'singup.jinja',{
        'form':UserCreationForm
        })
    else:
        if request.POST['password1']== request.POST['password2']:
            try:
                # Resgistra usuario
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request,user)
                return redirect('Lista')


            except IntegrityError:
                return render(request,'singup.jinja',{
                    'form':UserCreationForm,
                'error':'El usuario ya existe'})

        return render(request,'singup.jinja',{
                'form':UserCreationForm,
                'error':'Las contrase;as no coinciden'
                })

def singout(request):
    logout(request)
    return redirect('Inicio')

def signin(request):
    if request.method == 'GET':
        return render(request,'signin.jinja',{'form':AuthenticationForm})
    else:
        user = authenticate(request,username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request,'signin.jinja',
                          {'form':AuthenticationForm,
                           'error':"Tu usuario o contrasena  esta incorrecta"})
        else:
            login(request,user)
            return redirect('Lista')




def Departamentos(request):
    departamentos = Departamento.objects.all()
    departamentos_dict = [{
        "id":dep.pk,"Descripcion":dep.descripcion
    } for dep in departamentos]
    return render(request,'departamentos.jinja',{"table_body":departamentos_dict})

def Cargos(request):
    cargos = Cargo.objects.all()
    cargos_dict = [{
        "id":dep.pk,"Descripcion":dep.descripcion
    } for dep in cargos]
    return render(request,'cargos.jinja',{"table_body":cargos_dict})

def Contrato(request):
    contratos = TipoContrato.objects.all()
    contratos_dict = [{
        "id":dep.pk,"Descripcion":dep.descripcion
    } for dep in contratos]
    return render(request,'contrato.jinja',{"table_body":contratos_dict})

def Nominas(request):
    nominas = Rol.objects.all()
    nominas_dict = [{
        "id":rol.pk,"Empleado":rol.empleado.nombre, "Anio Mes":rol.aniomes, "sueldo":rol.sueldo,
        "Horas Extra":rol.horas_extra,"Bono":rol.bono,"Iess":rol.iess,"Total":rol.tot_ing,
        "Descuento":rol.tot_des, "Neto":rol.neto
    } for rol in nominas]
    return render(request,'nominas.jinja',{"table_body":nominas_dict})

# Vistas de crear
def CrearEmpleado(request):
    if request.method == "POST":
        print("Hoyeee")
        formulario = EmpleadoForm(request.POST);
        if formulario.is_valid():
            nombre = formulario.cleaned_data['nombre']
            sueldo = formulario.cleaned_data['sueldo']
            cedula = formulario.cleaned_data['cedula']
            direccion = formulario.cleaned_data['direccion']
            sexo_choice = dict(Empleado.SEXO_CHOICES)
            sexo = sexo_choice[formulario.cleaned_data['sexo']]
            cargo = Cargo.objects.get(descripcion=formulario.cleaned_data['cargo'])
            departamento = Departamento.objects.get(descripcion=formulario.cleaned_data['departamento'])
            tipo_contrato = TipoContrato.objects.get(descripcion=formulario.cleaned_data['tipo_contrato'])
            empleado = Empleado(
                nombre=nombre, cedula=cedula, direccion=direccion,sexo=sexo,
                cargo=cargo, departamento=departamento,tipo_contrato=tipo_contrato, sueldo = sueldo
            )
            empleado.save()
            return redirect("Lista")
        else:
            return HttpResponse(formulario.errors.as_json())
    else:
        formulario = EmpleadoForm()
    return render(request,'crear_empleado.jinja',{'formulario':formulario})

def CrearNominas(request):
    if request.method == "POST":
        formulario = RolPago(request.POST);
        if formulario.is_valid():
            empleado = Empleado.objects.get(nombre=formulario.cleaned_data["empleado"])
            aniomes = formulario.cleaned_data["aniomes"]
            horas_extra = formulario.cleaned_data['horas_extra']
            bono = float(formulario.cleaned_data['bono'])
            sueldo = float(empleado.sueldo)
            iess = 0.0945
            tot_ing= sueldo + float(horas_extra) + bono
            tot_des = iess * sueldo
            neto = tot_ing - tot_des
            Nomina = Rol(empleado=empleado, aniomes=aniomes, horas_extra=int(horas_extra), bono=bono,
                         sueldo=sueldo,iess=iess * float(100),tot_ing=tot_ing,tot_des=tot_des,neto=neto)
            Nomina.save()
            return redirect("Lista")
    else:
        formulario = RolPago()
    return render(request,'crear_nominas.jinja',{'formulario':formulario})

def CrearCargo(request):
    if request.method == "POST":
        formulario = FormCargo(request.POST);
        if formulario.is_valid():
            descripcion = formulario.cleaned_data['descripcion']
            cargo = Cargo(descripcion=descripcion)
            cargo.save()
            return redirect("Lista")
    else:
        formulario = FormCargo()
    return render(request,'crear_cargo.jinja',{'formulario':formulario,"tipo":"Cargo","name":"Crear_Cargo"})

def CrearDepartamento(request):
    if request.method == "POST":
        formulario = FormDepartamento(request.POST);
        if formulario.is_valid():
            descripcion = formulario.cleaned_data['descripcion']
            departamento = Departamento(descripcion=descripcion)
            departamento.save()
            return redirect("Lista")
    else:
        formulario = FormDepartamento()
    return render(request,'crear_cargo.jinja',{'formulario':formulario, "tipo":"Departamento","name":"Crear_Departamento"})

def CrearContrato(request):
    if request.method == "POST":
        formulario = FormContrato(request.POST);
        if formulario.is_valid():
            descripcion = formulario.cleaned_data['descripcion']
            contrato = TipoContrato(descripcion=descripcion)
            contrato.save()
            return redirect("Lista")
    else:
        formulario = FormCargo()
    return render(request,'crear_cargo.jinja',{'formulario':formulario, "tipo":"Contrato","name":"Crear_Contrato"})
# Vistas de actulizar
def UpdateEmpleado(request,id):
    if request.method == "POST":
        formulario = EmpleadoForm(request.POST,instance=Empleado.objects.get(pk=id))
        if formulario.is_valid():
            empleado = formulario.save(commit=False)
            SEXO_CHOICES = dict(Empleado.SEXO_CHOICES)
            sexo = SEXO_CHOICES[formulario.cleaned_data['sexo']]
            empleado.sexo = sexo
            empleado.save()
            return HttpResponseRedirect("/listado/")
    else:
        empleado = Empleado.objects.get(pk=id)
        formulario = EmpleadoForm(instance=empleado)
    return render(request,'update_empleado.jinja',{"formulario":formulario, 'id':id})

def UpdateNomina(request,id):
    if request.method == "POST":
        formulario = RolPago(request.POST,instance=Rol.objects.get(pk=id))
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect("/listado/")
    else:
        empleado = Rol.objects.get(pk=id)
        formulario = RolPago(instance=empleado)
    return render(request,'update_nomina.jinja',{"formulario":formulario, 'id':id})

def UpdateDepartamento(request,id):
    if request.method == "POST":
        formulario = FormDepartamento(request.POST,instance=Departamento.objects.get(pk=id))
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect("/listado/")
    else:
        departamento = Departamento.objects.get(pk=id)
        formulario = FormDepartamento(instance=departamento)

    return render(request,'update_cargo.jinja',{'formulario':formulario, "tipo":"Departamento","name":"Update_Departamento",'id':id})


def UpdateCargo(request,id):
    if request.method == "POST":
        formulario = FormCargo(request.POST,instance=Cargo.objects.get(pk=id))
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect("/listado/")
    else:
        cargo = Cargo.objects.get(pk=id)
        formulario = FormCargo(instance=cargo)
    return render(request,'update_cargo.jinja',{'formulario':formulario, "tipo":"Cargo","name":"Update_Cargo",'id':id})

def UpdateContrato(request,id):
    if request.method == "POST":
        formulario = FormContrato(request.POST,instance=TipoContrato.objects.get(pk=id))
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect("/listado/")
    else:
        contrato = TipoContrato.objects.get(pk=id)
        formulario = FormCargo(instance=contrato)

nomina/templates/Inicio.jinja
{% extends 'index.jinja' %}

{% block titulo %}
  <title>Inicio</title>
{% endblock titulo %}

{% block body %}
  <div class="Encabezado bg-dark mt-5">
    <div class="container text-light p-5">
      <div class="row">
        <div
          class="col d-flex flex-column justify-content-center align-items-center gap-2"
        >
          <h2>Gestion de nominas</h2>
          <button class=" btn btn-primary"   >Inicia tu gestion</button>
        </div>
        <div class="col">
          <img
            class="mx-auto d-block"
            alt="Imagen de inicio"
            src="https://static.wikia.nocookie.net/hollowknight/images/2/24/Millibelle.png/revision/latest?cb=20180528034357"
          />
        </div>
      </div>
    </div>
  </div>
  <div class="Seccion1 mt-5">
    <h1 class="text-center">Porque gestionar con nosotros?</h1>
    <div class="mx-auto d-block p-3" style="width: 35em;">
      <p class="fs-4">
        Nuestro equipo desarrollo una logica preciza para que puedas agregar a
        tus empleados y poder generar tu nominas de pago de la manera mas comoda
        posible y segura...
      </p>
    </div>
  </div>
  <div class="Seccion2 mt-5 bg-dark p-5">
    <div class="container">
      <div class="row gap-3">
        <div class="col">
          <div class="card text-center text-bg-dark border-light">
            <div class="card-body">
              <h2 class="card-title">Empleados:</h2>
              <p class="btn disabled">1</p>
              <p class="fs-4 card-text">Empleados registrados</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card text-center text-bg-dark border-light">
            <div class="card-body">
              <h2 class="">Cargos:</h2>
              <p class="btn disabled">3</p>
              <p class="fs-4 card-text">Cargos disponibles</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card text-center text-bg-dark border-light">
            <div class="card-body">
              <h2 class="">Nominas</h2>
              <p class="btn disabled">0</p>
              <p class="fs-4 card-text">Nominas generadas</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock body %}

nomina/templates/cargos.jinja
{% extends 'index.jinja' %}

{% block titulo %}
  <title>Listado de Cargos</title>
{% endblock titulo %}

{% block body %}
  <div class="container mt-3">
    {% include 'componentes/tab.jinja' with empleado="" nominas="" depa="" cargo="active" contrato="" %}
    <div class="row">
      <h1>Listado de Cargos</h1>
    </div>
    <div class="row">
      {% include 'componentes/tabla.jinja' with table_body=table_body ruta="Update_Cargo" modelo="Cargo" %}
    </div>
    {% include 'componentes/add-btn.jinja' with name="Crear_Cargo" %}
  </div>
{% endblock body %}

nomina/templates/contrato.jinja
{% extends 'index.jinja' %}

{% block titulo %}
  <title>Listado de Contratos</title>
{% endblock titulo %}

{% block body %}
  <div class="container mt-3">
    {% include 'componentes/tab.jinja' with empleado="" nominas="" depa="" cargo="" contrato="active" %}
    <div class="row">
      <h1>Listado de Cargos</h1>
    </div>
    <div class="row">
      {% include 'componentes/tabla.jinja' with table_body=table_body ruta="Update_Contrato" modelo="Contrato" %}
    </div>
    {% include 'componentes/add-btn.jinja' with name="Crear_Contrato" %}
  </div>
{% endblock body %}

nomina/templates/crear_cargo.jinja
{% extends 'index.jinja' %}

{% block titulo %}
  <title>Crear {{ tipo }}</title>
{% endblock titulo %}

{% block body %}
  <div class="container">
    <div class="card p-4 mx-auto d-block" style="width: 40em;">
      <h2 class="text-center">Crear Un {{ tipo }}</h2>
      <form method="post" action="{% url name %}">
        {% csrf_token %}
        <div class="gap-3 d-flex flex-column">
          <div class="row">
            <div class="col">
              <label class="form-lable" for="id_descripcion">{{ tipo }}</label>
              {{ formulario.descripcion }}
            </div>
          </div>
          <div class="row">
            <button class="btn-primary btn" typr="submit">Crear</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock body %}

nomina/templates/crear_empleado.jinja
{% extends 'index.jinja' %}

{% block titulo %}
  <title>Crear Empleado</title>
{% endblock titulo %}

{% block body %}
  <div class="container">
    <div class="card p-4 mx-auto d-block" style="width: 40em;">
      <h2 class="text-center">Crear Empleado</h2>
      <form method="post" action="{% url 'Crear_Empleado' %}">
        {% csrf_token %}
        <div class="gap-3 d-flex flex-column">
          <div class="row">
            <div class="col">
              <label class="form-lable" for="id_nombre">Nombre</label>
              {{ formulario.nombre }}
            </div>
            <div class="col">
              <label class="form-lable" for="id_cedula">cedula</label>
              {{ formulario.cedula }}
            </div>
          </div>
          <div class="row">
            <div class="col">
              <label class="form-label" for="id_sueldo">Sueldo</label>
              {{ formulario.sueldo }}
            </div>
            <div class="col">
              <label class="form-label" for="id_sexo">Horas Extras</label>
              {{ formulario.sexo }}
            </div>
          </div>
          <div class="row">
            <div class="col">
              <label class="form-label" for="id_cargo">Cargo</label>
              {{ formulario.cargo }}
            </div>
            <div class="col">
              <label class="form-label" for="id_departamento"
                >Departamento</label
              >
              {{ formulario.departamento }}
            </div>
            <div class="col">
              <label class="form-label" for="id_tipo_contrato">Contrato</label>
              {{ formulario.tipo_contrato }}
            </div>
            <div class="col">
              <label class="form-label" for="id_tipo_direccion"
                >direccion</label
              >
              {{ formulario.direccion }}
            </div>
          </div>
          <div class="row">
            <button class="btn-primary btn" type="submit">Crear</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock body %}

nomina/templates/crear_nominas.jinja
{% extends 'index.jinja' %}

{% block titulo %}
  <title>Crear Nomina</title>
{% endblock titulo %}

{% block body %}
  <div class="container">
    <div class="card p-4 mx-auto d-block" style="width: 40em;">
      <h2 class="text-center">Crear Rol De Pago</h2>
      <form method="post" action="{% url 'Crear_Nomina' %}">
        {% csrf_token %}
        <div class="gap-3 d-flex flex-column">
          <div class="row">
            <div class="col">
              <label class="form-lable" for="id_empleado">Empleado</label>
              {{ formulario.empleado }}
            </div>
            <div class="col">
              <label class="form-lable" for="id_aniomes">Anio Mes</label>
              {{ formulario.aniomes }}
            </div>
          </div>
          <div class="row">
            <div class="col">
              <label class="form-label" for="id_bono">Bono</label>
              {{ formulario.bono }}
            </div>
            <div class="col">
              <label class="form-label" for="id_horas_extra"
                >Horas Extras</label
              >
              {{ formulario.horas_extra }}
            </div>
          </div>
          <div class="row">
            <button class="btn-primary btn" typr="submit">Crear</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock body %}

nomina/templates/departamentos.jinja
{% extends 'index.jinja' %}

{% block titulo %}
  <title>Listado de Departamentos</title>
{% endblock titulo %}

{% block body %}
  <div class="container mt-3">
    {% include 'componentes/tab.jinja' with empleado="" nominas="" depa="active" cargo="" contrato="" %}
    <div class="row">
      <h1>Listado de Departamentos</h1>
    </div>
    <div class="row">
      {% include 'componentes/tabla.jinja' with table_body=table_body ruta="Update_Departamento" modelo="Departamento" %}
    </div>
    {% include 'componentes/add-btn.jinja' with name="Crear_Departamento" %}
  </div>
{% endblock body %}

nomina/templates/update_cargo.jinja
{% extends 'index.jinja' %}

{% block titulo %}
  <title>Actualizar {{ tipo }}</title>
{% endblock titulo %}

{% block body %}
  <div class="container">
    <div class="card p-4 mx-auto d-block" style="width: 40em;">
      <h2 class="text-center">Actualiza Un {{ tipo }}</h2>
      <form method="post" action="{% url name id %}">
        {% csrf_token %}
        <div class="gap-3 d-flex flex-column">
          <div class="row">
            <div class="col">
              <label class="form-lable" for="id_descripcion">{{ tipo }}</label>
              {{ formulario.descripcion }}
            </div>
          </div>
          <div class="row">
            <button class="btn-primary btn" typr="submit">Actualiza</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock body %}

nomina/templates/update_empleado.jinja
{% extends 'index.jinja' %}

{% block titulo %}
  <title>Actualizar Empleado</title>
{% endblock titulo %}

{% block body %}
  <div class="container">
    <div class="card p-4 mx-auto d-block" style="width: 40em;">
      <h2 class="text-center">Actualizar Empleado</h2>
      <form method="post" action="{% url 'Update_Empleado' id %}">
        {% csrf_token %}
        <div class="gap-3 d-flex flex-column">
          <div class="row">
            <div class="col">
              <label class="form-lable" for="id_nombre">Nombre</label>
              {{ formulario.nombre }}
            </div>
            <div class="col">
              <label class="form-lable" for="id_cedula">cedula</label>
              {{ formulario.cedula }}
            </div>
          </div>
          <div class="row">
            <div class="col">
              <label class="form-label" for="id_sueldo">Sueldo</label>
              {{ formulario.sueldo }}
            </div>
            <div class="col">
              <label class="form-label" for="id_sexo">Horas Extras</label>
              {{ formulario.sexo }}
            </div>
          </div>
          <div class="row">
            <div class="col">
              <label class="form-label" for="id_cargo">Cargo</label>
              {{ formulario.cargo }}
            </div>
            <div class="col">
              <label class="form-label" for="id_departamento"
                >Departamento</label
              >
              {{ formulario.departamento }}
            </div>
            <div class="col">
              <label class="form-label" for="id_tipo_contrato">Contrato</label>
              {{ formulario.tipo_contrato }}
            </div>
            <div class="col">
              <label class="form-label" for="id_tipo_direccion"
                >direccion</label
              >
              {{ formulario.direccion }}
            </div>
          </div>
          <div class="row">
            <button class="btn-primary btn" type="submit">Actualizar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock body %}

nomina/templates/update_nomina.jinja
{% extends 'index.jinja' %}

{% block titulo %}
  <title>Actualizar Nomina</title>
{% endblock titulo %}

{% block body %}
  <div class="container">
    <div class="card p-4 mx-auto d-block" style="width: 40em;">
      <h2 class="text-center">Actualizar Rol De Pago</h2>
      <form method="post" action="{% url 'Update_Nomina' id %}">
        {% csrf_token %}
        <div class="gap-3 d-flex flex-column">
          <div class="row">
            <div class="col">
              <label class="form-lable" for="id_empleado">Empleado</label>
              {{ formulario.empleado }}
            </div>
            <div class="col">
              <label class="form-lable" for="id_aniomes">Anio Mes</label>
              {{ formulario.aniomes }}
            </div>
          </div>
          <div class="row">
            <div class="col">
              <label class="form-label" for="id_bono">Bono</label>
              {{ formulario.bono }}
            </div>
            <div class="col">
              <label class="form-label" for="id_horas_extra"
                >Horas Extras</label
              >
              {{ formulario.horas_extra }}
            </div>
          </div>
          <div class="row">
            <button class="btn-primary btn" typr="submit">Actualizar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock body %}